package app;

import java.sql.*;

public class Category extends ActiveDomainObject {
	
	private int categoryID;
	private String name;
	
	private static final int NOID = -1;
	
	// constructor for object with new category
	public Category(String name) {
		this.categoryID = NOID;
		this.name = name;
	}
	
	// constructor for object with existing category
	public Category(int categoryID) {
		this.categoryID = categoryID;
	}
	
	public int getCategoryID() {
		return this.categoryID;
	}
	
	public void setCategoryID(int categoryID) {
		this.categoryID = categoryID;
	}
	
	@Override
	public void initialize(Connection conn) {
		try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT Name FROM Category WHERE CategoryID=" + categoryID);
            while (rs.next()) {
            	name =  rs.getString("Name");
            }

        } catch (Exception e) {
            System.out.println("db error during select of category= "+e);
            return;
        }
	}
	@Override
	public void refresh(Connection conn) {
		initialize (conn);
	}
	@Override
	public void save(Connection conn) {
		try {    
            Statement stmt = conn.createStatement(); 
            stmt.executeUpdate("INSERT INTO Category (Name) VALUES "
            		+ "('"+name+"')", stmt.RETURN_GENERATED_KEYS);
            
            // update object's id to autogenerated id in database
        	ResultSet generatedKeys = stmt.getGeneratedKeys();
        	if (generatedKeys.next()) {
        		this.setCategoryID((generatedKeys.getInt(1)));
        	} 
            
        } catch (Exception e) {
            System.out.println("db error during insert of category="+e);
            return;
        }
		
	}

}
