package app;

import java.sql.*;

public class Person extends ActiveDomainObject {
	
	private int personID;
	private String name;
	private String birthYear;
	private String birthCountry;
	
	private static final int NOID = -1;
	
	// constructor for object with new person
	public Person(String name, String birthYear, String birthCountry ) {
		this.personID = NOID;
		this.name = name;
		this.birthYear = birthYear;
		this.birthCountry = birthCountry;
	}
	
	// constructor for object with existing person
	public Person(int personID) {
		this.personID = personID;
	}
	
	public int getPersonID() {
		return this.personID;
	}
	
	public void setPersonID(int personID) {
		this.personID = personID;
	}
	
	@Override
	public void initialize(Connection conn) {
		try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT Name, BirthYear, BirthCountry FROM Person WHERE PersonID=" + personID);
            while (rs.next()) {
            	name =  rs.getString("Name");
            	birthYear =  rs.getString("BirthYear");
            	birthCountry =  rs.getString("BirthCountry");
            }

        } catch (Exception e) {
            System.out.println("db error during select of person= "+e);
            return;
        }
	}
	
	@Override
	public void refresh(Connection conn) {
		initialize (conn);
	}
	
	@Override
	public void save(Connection conn) {
		try {    
            Statement stmt = conn.createStatement(); 
            stmt.executeUpdate("INSERT INTO Person (Name, BirthYear, BirthCountry) VALUES ('"+name+"','"+birthYear+"','"+birthCountry+"')"
            		, stmt.RETURN_GENERATED_KEYS);
            
            // update object's id to autogenerated id in database
        	ResultSet generatedKeys = stmt.getGeneratedKeys();
        	if (generatedKeys.next()) {
        		this.setPersonID((generatedKeys.getInt(1)));
        	} 
            
        } catch (Exception e) {
            System.out.println("db error during insert of person="+e);
            return;
        }
		
	}

}
