package app;

import java.sql.*;

public class Series extends ActiveDomainObject {
	
	private int seriesID;
	private String name;
	private int numberOfSeasons;
	private int numberOfEpisodes;
	
	private static final int NOID = -1;
	
	// constructor for object with new category
	public Series(String name, int numberOfSeasons, int numberOfEpisodes) {
		this.seriesID = NOID;
		this.name = name;
		this.numberOfSeasons = numberOfSeasons;
		this.numberOfEpisodes = numberOfEpisodes;
	}
	
	// constructor for object with existing category
	public Series(int seriesID) {
		this.seriesID = seriesID;
	}
	
	public int getSeriesID() {
		return this.seriesID;
	}
	
	public void setSeriesID(int seriesID) {
		this.seriesID = seriesID;
	}
	
	@Override
	public void initialize(Connection conn) {
		try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT Name, NumberOfSeasons, NumberOfEpisodes FROM Series WHERE SeriesID=" + seriesID);
            while (rs.next()) {
            	name =  rs.getString("Name");
            	numberOfSeasons = rs.getInt("NumberOfSeasons");
            	numberOfEpisodes = rs.getInt("NumberOfEpisodes");
            }

        } catch (Exception e) {
            System.out.println("db error during select of series= "+e);
            return;
        }
	}

	@Override
	public void refresh(Connection conn) {
		initialize (conn);
	}

	@Override
	public void save(Connection conn) {
		try {    
            Statement stmt = conn.createStatement(); 
            stmt.executeUpdate("INSERT INTO Series (Name, NumberOfSeasons, NumberOfEpisodes) VALUES "
            		+ "('"+name+"',"+numberOfSeasons+","+numberOfEpisodes+")", stmt.RETURN_GENERATED_KEYS);
            
            // update object's id to autogenerated id in database
        	ResultSet generatedKeys = stmt.getGeneratedKeys();
        	if (generatedKeys.next()) {
        		this.setSeriesID(generatedKeys.getInt(1));
        	} 
            
        } catch (Exception e) {
            System.out.println("db error during insert of series="+e);
            return;
        }
		
		
	}

}
